#!/usr/bin/env cwl-runner
cwlVersion: v1.2
class: CommandLineTool

label: scGPT Fine-tuning Tool
doc: Runs scGPT fine-tuning script with config, data, and model inputs

inputs:
  script:
    type: File
    inputBinding:
      position: 0
    doc: Python script to execute (test_scGPT.py)
  
  config:
    type: File
    doc: YAML configuration file
  
  data_dir:
    type: Directory
    doc: Directory containing data files (c_data.h5ad, filtered_ms_adata.h5ad)
  
  model_dir:
    type: Directory
    doc: Directory containing model files (best_model.pt, vocab.json, args.json)

outputs:
  output_files:
    type: File[]
    outputBinding:
      glob: "output_*.txt"
    doc: Output files generated by the script

stdout: fine_tuning.stdout
stderr: fine_tuning.stderr

baseCommand: python3

arguments:
  - $(inputs.script.path)

requirements:
  - class: DockerRequirement
    dockerPull: bh2025scllmsp30-scgpt:latest
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.script)
        writable: false
      - entry: $(inputs.config)
        writable: false
      - entryname: data
        entry: $(inputs.data_dir)
        writable: false
      - entryname: pan_cancer
        entry: $(inputs.model_dir)
        writable: false
  - class: EnvVarRequirement
    envDef:
      - envName: CONFIG
        envValue: config.yml

